spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://testexample-db:5432/postgres
    username: postgres
    password: mysecretpassword
    
