version: "3.3"
services:
  app:
    build: docker/app
    ports:
      - 8111:8080
      - 8001:8001
    volumes:
      - ./target/testexample-0.0.1-SNAPSHOT.jar:/opt/testexample.jar:ro
      - ./docker/app/application.yml:/opt/application.yml:ro
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
    networks:
      - testexample
    container_name: testexample-app
      
  db:
    image: postgres:latest
    restart: always
    hostname: testexample-db
    container_name: testexample-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - testexample

networks:
  testexample:
    ipam:
      config:
        - subnet: 192.168.49.0/24
